version: "3.9"
services:
  client:
    build:
      context: .
      dockerfile: Client.Dockerfile
    ports:
      - "5000:80"
    environment:
      - TestPayment__ServiceUrl=http://server:80
 
  server:
    build:
      context: .
      dockerfile: Server.Dockerfile
    ports:
      - "5001:80"


